# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster-custom"

# My zsh custom folder with a bunch of plugins and theme
ZSH_CUSTOM=$HOME/.zsh-custom

# Get quick access to dotfiles directory by typing `cd $MYDOTFILES`
export MYDOTFILES="${$(readlink $ZSH_CUSTOM)%\/*\/*}"

# Custom plugins that snould not be tracked by git can be added to
# ~/.zsh-profile like this:
# plugins += (plugin1 plugin2)
plugins=(git pip zsh-syntax-highlighting colored-man-pages docker)

export PATH=$PATH:$HOME/.local/bin:$HOME/bin

# Custom commands and plugins that should not be tracked by git.
# NOTE: it's important to source this file BEFORE oh-my-zsh.sh if it adds some
# plugins and/or redefines ZSH_THEME. Otherwise it will not work.
source ~/.zsh-local

source $ZSH/oh-my-zsh.sh

# agnoster-custom theme already shows virtualenv section. So it can be skipped
export VIRTUAL_ENV_DISABLE_PROMPT=1

# To make colored-man-pages work properly
export GROFF_NO_SGR=1

# Check if vim is installed and redefine view to use $VIMRUNTIME/macros/less.sh
# It will be vim with syntax highlighting and all the stuff, but in readonly
# mode and with some redefined commands (especialy `q` - exit)
if command -v vim > /dev/null; then
  VIMRUNTIME=`vim -e -T dumb --cmd 'exe "set t_cm=\<C-M>"|echo $VIMRUNTIME|quit' | tr -d '\015' `
  alias view="$VIMRUNTIME/macros/less.sh"
fi

unsetopt share_history
